"""initial_schema"""
from alembic import op
import sqlalchemy as sa

revision = '9e1c02ec8729'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('at', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_at'), ['at'], unique=False)

    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('meetings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('host_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('starts', sa.Integer(), nullable=False),
    sa.Column('ends', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('guest_policy', sa.String(length=16), nullable=False),
    sa.Column('waiting_room', sa.Boolean(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.Integer(), nullable=True),
    sa.Column('ended_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meetings_starts'), ['starts'], unique=False)

    op.create_table('sessions',
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('expires', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('digest')
    )
    op.create_table('invitations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('encrypted_token', sa.Text(), nullable=False),
    sa.Column('expires', sa.Integer(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('reminder_sent', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('digest')
    )
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invitations_meeting_id'), ['meeting_id'], unique=False)

    op.create_table('guest_sessions',
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('invitation_id', sa.String(length=36), nullable=False),
    sa.Column('expires', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['invitation_id'], ['invitations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('digest')
    )
    op.create_table('participants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('identity', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('invitation_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('connected', sa.Boolean(), nullable=False),
    sa.Column('raised', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.Integer(), nullable=True),
    sa.Column('left_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invitation_id'], ['invitations.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'identity')
    )
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participants_meeting_id'), ['meeting_id'], unique=False)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participants_meeting_id'))

    op.drop_table('participants')
    op.drop_table('guest_sessions')
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invitations_meeting_id'))

    op.drop_table('invitations')
    op.drop_table('sessions')
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meetings_starts'))

    op.drop_table('meetings')
    op.drop_table('users')
    op.drop_table('company')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_at'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
